Add active plan status to side bar
kausaltech/kausal-watch pull request #298
Opened 2024-11-26 07:27 UTC by MWargelin

Adds status information about the active plan to the status bar.

The design created for this feature can be found here: https://app.asana.com/0/1206017643443542/1208607227000757/f

2024-11-26 07:28 UTC, MWargelin commented on admin_site/templates/wagtailadmin/base.html
> +            {% endif %}
Did I get the logic right here, i.e. is `active_plan.actions_locked` what was meant by the plan being locked?

2024-11-26 08:08 UTC, tituomin requested changes
I will still test how this looks. Left some requests.

2024-11-26 08:08 UTC, tituomin commented on admin_site/templates/wagtailadmin/base.html
> +            {% endif %}
Actually we haven't implemented the locking yet. `actions_locked` was a good guess but we plan to have some feature which locks everything, not just actions.

2024-11-26 08:08 UTC, tituomin commented on admin_site/templates/wagtailadmin/base.html
> +            {% endif %}
This is good, but I realized there is a bug in Plan.is_live. It should compare the date to the current date. But not a problem wrt this PR.

Another thing is that I think if it's not live, we want to display that info as well, we could use the term "draft" for the opposite state. Or "internal" is another option.

2024-11-26 08:08 UTC, tituomin commented on admin_site/templates/wagtailadmin/base.html
> +                    <span class="active-plan-live">live</span>
We should localize these UI strings.

2024-11-26 08:08 UTC, tituomin commented on admin_site/templates/wagtailadmin/base.html
> +                <div class="active-plan-locked">{% icon name="lock" %}</div>
We probably want an aria-attribute for accessibility, some verbal description of the state in addition to the icon

2024-11-26 08:08 UTC, tituomin commented on admin_site/templates/wagtailadmin/base.html
> +            {% endif %}
It's good to have this for testing though, and we might just comment it out for now, before deploying.

2024-11-26 12:26 UTC, MWargelin commented on admin_site/templates/wagtailadmin/base.html
> +            {% endif %}
I thought it was something like that, good that that was cleared. I commented the code out for now with a TODO message.

2024-11-26 12:29 UTC, MWargelin commented on admin_site/templates/wagtailadmin/base.html
> +            {% endif %}
Good catch with the `is_live` bug. Seemed like a small thing so fixed it here anyway, is this what you meant? 43ee9803182fb97637651f2b8156a16b111c866f

I changed this now to print "draft" if the plan is not live.

2024-11-26 12:30 UTC, MWargelin commented on admin_site/templates/wagtailadmin/base.html
> +                    <span class="active-plan-live">live</span>
localised the strings :+1:

2024-11-26 12:32 UTC, MWargelin commented on admin_site/templates/wagtailadmin/base.html
> +                <div class="active-plan-locked">{% icon name="lock" %}</div>
I'm not very familiar with aria and accessibility in general, I added `aria-label` that says `locked plan` (translated), does that sound right?

2024-12-02 08:59 UTC, MWargelin commented
@tituomin I believe I've now implemented all the requested changes, is this good to go now?

2024-12-02 13:12 UTC, merged