Remove duplicate plan menu item
kausaltech/kausal-watch pull request #305
Opened 2024-12-14 16:49 UTC by bbliem

This (and removing the associated modeladmin classes) required some changes to the tests.

2024-12-16 08:10 UTC, MWargelin commented on actions/wagtail_admin.py
> +    def user_has_permission_for_instance(self, user: AbstractBaseUser, action: str, instance: Model) -> bool:
I think this method doesn't actually get called, at least when I add a line that prints something and then open the `Plans` list view, nothing gets printed. If I add a `user_has_permission` method here that prints something, then the prints appear to the console when I open the Plans listing view.

I once dived into this myself and seems like for most of the time Wagtail doesn't call `user_has_permission_for_instance` when checking permissions, instead it calls `user_has_permission`. The best way I found to work around that was to define a custom `user_has_permission` method in the view that then calls `user_has_permission_for_instance`, like here: https://github.com/kausaltech/kausal-watch-private/blob/main/content/wagtail_admin.py#L48 , although I'm not sure if that works for what you were thinking of...

2024-12-16 11:06 UTC, MWargelin commented on actions/wagtail_admin.py
> +        assert isinstance(user, User)
Kind of more general question here, I've seen a lot of `assert`s around our code, but to me raising errors seems like the more natural/pythonic way of doing these kind of checks. Is there some rationale for using asserts?

2024-12-16 11:10 UTC, MWargelin requested changes
Looks good, but had a couple of questions :slightly_smiling_face:

2024-12-20 09:24 UTC, bbliem commented on actions/wagtail_admin.py
> +        assert isinstance(user, User)
I try to use assertions only to express conditions that necessarily hold due to our application logic (or at least should hold unless there is some bug). I usually do this in situations where the code would crash later on anyway if the assertion did not hold. For example, here, if `user` is not a `User` instance, I suppose the code would crash in the next line when we try to call `user.get_active_admin_plan()`. I think using assertions this way is nicer than just waiting for the crash because (a) it expresses my intentions when I wrote the code, and (b) if the assertion does not hold, we get an error message that allow us to find the source of the problem faster.

Assertions should not be used in cases where omitting the assertion could lead to unexpected results (e.g., because the code in fact does not crash if the assertion does not hold), since we can't always rely on the assertions being executed. But I try not to use them in those cases. Let me know if you found a place where I do.

Another reason why I often use assertions -- and probably this is the reason for this particular one -- is to make the type checker shut up because it sometimes can't figure things out that we can.

2025-01-02 07:17 UTC, MWargelin commented on actions/wagtail_admin.py
> +        assert isinstance(user, User)
Alright, good to know, this was a new concept for me :+1:

2025-01-02 07:20 UTC, MWargelin commented on actions/wagtail_admin.py
> +    def user_has_permission_for_instance(self, user: AbstractBaseUser, action: str, instance: Model) -> bool:
This might have got forgotten, any comments for this?

2025-01-10 17:56 UTC, bbliem commented on actions/wagtail_admin.py
> +    def user_has_permission_for_instance(self, user: AbstractBaseUser, action: str, instance: Model) -> bool:
You're right, it doesn't seem to get called. It's a bit strange, but the entire permission policy doesn't seem to do much. Indeed, I can remove it and the results are still as they should be, it seems: for example, a plan admin can't edit plans other than their own.

I removed this permission policy.

2025-01-10 18:01 UTC, bbliem commented
I removed the permission policy altogether. I'm not entirely sure why, but the permissions still seem to be handled as they should. Do you have any idea why? Just requested another review in case I missed something. If you don't have any objections to my removing the permission policy, let's get this PR merged.

2025-01-13 08:55 UTC, MWargelin commented
> I removed the permission policy altogether. I'm not entirely sure why, but the permissions still seem to be handled as they should. Do you have any idea why? Just requested another review in case I missed something. If you don't have any objections to my removing the permission policy, let's get this PR merged.

I'm guessing the index view listing works thanks to using [`PlanFilter`](https://github.com/kausaltech/kausal-watch-private/blob/3f1054fde1329f54818a86d4cd0bb5d84a8b2ded/actions/wagtail_admin.py#L597) and when you try to edit a plan it switches over to modeladmin views and the [modeladmin permission helper kicks in](https://github.com/kausaltech/kausal-watch-private/pull/305/files#diff-9e8d5025390277e22dbbcbd60605f7cc5f52b39806e9b97653532da27c8d35ccR179)?

But yeah the permissions seem to work without the permission policy as well, so maybe we should merge this now. We can work on the permission policy once this is fully migrated to snippets.

2025-01-13 08:55 UTC, MWargelin approved these changes

2025-01-14 08:46 UTC, merged